import type {ImageSourcePropType} from 'react-native';

export const expeditionVisuals = {
  baseCampBackdrop: require('./images/expedition-basecamp-backdrop.png') as ImageSourcePropType,
  emptyTrailBackdrop: require('./images/expedition-empty-savanna.png') as ImageSourcePropType,
  briefingCards: {
    places: require('./images/briefing-places-field-card.png') as ImageSourcePropType,
    species: require('./images/briefing-species-field-card.png') as ImageSourcePropType,
    challenge: require('./images/briefing-challenge-field-card.png') as ImageSourcePropType,
  },
  guides: {
    leo: require('./images/guide-sunmane-leo.png') as ImageSourcePropType,
    ella: require('./images/guide-canopy-ella.png') as ImageSourcePropType,
    chee: require('./images/guide-swift-chee.png') as ImageSourcePropType,
    koda: require('./images/guide-forest-koda.png') as ImageSourcePropType,
  },
  reserves: {
    serengeti: require('./images/reserve-serengeti-trail.png') as ImageSourcePropType,
    kruger: require('./images/reserve-kruger-trail.png') as ImageSourcePropType,
    yellowstone: require('./images/reserve-yellowstone-trail.png') as ImageSourcePropType,
    galapagos: require('./images/reserve-galapagos-trail.png') as ImageSourcePropType,
    banff: require('./images/reserve-banff-trail.png') as ImageSourcePropType,
    komodo: require('./images/reserve-komodo-trail.png') as ImageSourcePropType,
    kaziranga: require('./images/reserve-kaziranga-trail.png') as ImageSourcePropType,
    fiordland: require('./images/reserve-fiordland-trail.png') as ImageSourcePropType,
    torresDelPaine: require('./images/reserve-torres-paine-trail.png') as ImageSourcePropType,
    etosha: require('./images/reserve-etosha-trail.png') as ImageSourcePropType,
    ranthambore: require('./images/reserve-ranthambore-trail.png') as ImageSourcePropType,
    denali: require('./images/reserve-denali-trail.png') as ImageSourcePropType,
    chobe: require('./images/reserve-chobe-trail.png') as ImageSourcePropType,
    bialowieza: require('./images/reserve-bialowieza-trail.png') as ImageSourcePropType,
    kakadu: require('./images/reserve-kakadu-trail.png') as ImageSourcePropType,
    everglades: require('./images/reserve-everglades-trail.png') as ImageSourcePropType,
    bwindi: require('./images/reserve-bwindi-trail.png') as ImageSourcePropType,
    greatBarrierReef: require('./images/reserve-barrier-reef-trail.png') as ImageSourcePropType,
    arenal: require('./images/reserve-arenal-trail.png') as ImageSourcePropType,
    addo: require('./images/reserve-addo-trail.png') as ImageSourcePropType,
    sumatranRhino: require('./images/reserve-sumatran-rhino-trail.png') as ImageSourcePropType,
    canaima: require('./images/reserve-canaima-trail.png') as ImageSourcePropType,
    svalbard: require('./images/reserve-svalbard-trail.png') as ImageSourcePropType,
    pantanal: require('./images/reserve-pantanal-trail.png') as ImageSourcePropType,
  },
  species: {
    africanLion: require('./images/species-african-lion-field.png') as ImageSourcePropType,
    africanElephant: require('./images/species-african-elephant-field.png') as ImageSourcePropType,
    cheetah: require('./images/species-cheetah-field.png') as ImageSourcePropType,
    zebra: require('./images/species-zebra-field.png') as ImageSourcePropType,
    giraffe: require('./images/species-giraffe-field.png') as ImageSourcePropType,
    bengalTiger: require('./images/species-bengal-tiger-field.png') as ImageSourcePropType,
    grayWolf: require('./images/species-gray-wolf-field.png') as ImageSourcePropType,
    polarBear: require('./images/species-polar-bear-field.png') as ImageSourcePropType,
    giantPanda: require('./images/species-giant-panda-field.png') as ImageSourcePropType,
    komodoDragon: require('./images/species-komodo-dragon-field.png') as ImageSourcePropType,
    galapagosTortoise: require('./images/species-galapagos-tortoise-field.png') as ImageSourcePropType,
    baldEagle: require('./images/species-bald-eagle-field.png') as ImageSourcePropType,
    greenSeaTurtle: require('./images/species-green-sea-turtle-field.png') as ImageSourcePropType,
    redEyedTreeFrog: require('./images/species-red-eyed-frog-field.png') as ImageSourcePropType,
    snowLeopard: require('./images/species-snow-leopard-field.png') as ImageSourcePropType,
    orangutan: require('./images/species-orangutan-field.png') as ImageSourcePropType,
  },
};
